[package]
name = "xdp-prog"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"
# Apache 2.0 is for user space code only
# Linux requires eBPF/XDP programs to be GPL-licensed

[lib]
name = "xdp_prog"
crate-type = ["cdylib"]

[dependencies]
anyhow = "1.0"

[build-dependencies]
bindgen = "0.64"