[package]
name = "xdp-server"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"

[dependencies]
libbpf-rs = "0.25"
anyhow = "1.0"
tokio = { version = "1.37", features = ["full"] }
nix = "0.27"
num_cpus = "1.13"

[build-dependencies]
bindgen = "0.64"