[package]
name = "xdp-server"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"

[dependencies]
libbpf-rs = "0.21"
tokio = { version = "1.37", features = ["full"] }
anyhow = "1.0"
num_cpus = "1.13"
nix = "0.26"

[build-dependencies]
bindgen = "0.64"